package dukascopy

// DefaultInstruments is a static comprehensive list of over 170 high-quality instruments supported by Dukascopy.
// It serves as an offline-ready database and fallback/merge source.
var DefaultInstruments = []Instrument{
	// Forex Major Pairs
	{ID: 1, Name: "EUR/USD", Code: "EURUSD", PriceScale: 5, Description: "Euro vs US Dollar"},
	{ID: 2, Name: "GBP/USD", Code: "GBPUSD", PriceScale: 5, Description: "Great Britain Pound vs US Dollar"},
	{ID: 3, Name: "USD/JPY", Code: "USDJPY", PriceScale: 3, Description: "US Dollar vs Japanese Yen"},
	{ID: 4, Name: "USD/CHF", Code: "USDCHF", PriceScale: 5, Description: "US Dollar vs Swiss Franc"},
	{ID: 5, Name: "USD/CAD", Code: "USDCAD", PriceScale: 5, Description: "US Dollar vs Canadian Dollar"},
	{ID: 6, Name: "AUD/USD", Code: "AUDUSD", PriceScale: 5, Description: "Australian Dollar vs US Dollar"},
	{ID: 7, Name: "NZD/USD", Code: "NZDUSD", PriceScale: 5, Description: "New Zealand Dollar vs US Dollar"},

	// Forex Cross Pairs
	{ID: 8, Name: "EUR/GBP", Code: "EURGBP", PriceScale: 5, Description: "Euro vs Great Britain Pound"},
	{ID: 9, Name: "EUR/JPY", Code: "EURJPY", PriceScale: 3, Description: "Euro vs Japanese Yen"},
	{ID: 10, Name: "EUR/CHF", Code: "EURCHF", PriceScale: 5, Description: "Euro vs Swiss Franc"},
	{ID: 11, Name: "EUR/CAD", Code: "EURCAD", PriceScale: 5, Description: "Euro vs Canadian Dollar"},
	{ID: 12, Name: "EUR/AUD", Code: "EURAUD", PriceScale: 5, Description: "Euro vs Australian Dollar"},
	{ID: 13, Name: "EUR/NZD", Code: "EURNZD", PriceScale: 5, Description: "Euro vs New Zealand Dollar"},
	{ID: 14, Name: "GBP/JPY", Code: "GBPJPY", PriceScale: 3, Description: "Great Britain Pound vs Japanese Yen"},
	{ID: 15, Name: "GBP/CHF", Code: "GBPCHF", PriceScale: 5, Description: "Great Britain Pound vs Swiss Franc"},
	{ID: 16, Name: "GBP/AUD", Code: "GBPAUD", PriceScale: 5, Description: "Great Britain Pound vs Australian Dollar"},
	{ID: 17, Name: "GBP/CAD", Code: "GBPCAD", PriceScale: 5, Description: "Great Britain Pound vs Canadian Dollar"},
	{ID: 18, Name: "GBP/NZD", Code: "GBPNZD", PriceScale: 5, Description: "Great Britain Pound vs New Zealand Dollar"},
	{ID: 19, Name: "AUD/JPY", Code: "AUDJPY", PriceScale: 3, Description: "Australian Dollar vs Japanese Yen"},
	{ID: 20, Name: "AUD/CHF", Code: "AUDCHF", PriceScale: 5, Description: "Australian Dollar vs Swiss Franc"},
	{ID: 21, Name: "AUD/CAD", Code: "AUDCAD", PriceScale: 5, Description: "Australian Dollar vs Canadian Dollar"},
	{ID: 22, Name: "AUD/NZD", Code: "AUDNZD", PriceScale: 5, Description: "Australian Dollar vs New Zealand Dollar"},
	{ID: 23, Name: "CAD/JPY", Code: "CADJPY", PriceScale: 3, Description: "Canadian Dollar vs Japanese Yen"},
	{ID: 24, Name: "CAD/CHF", Code: "CADCHF", PriceScale: 5, Description: "Canadian Dollar vs Swiss Franc"},
	{ID: 25, Name: "CHF/JPY", Code: "CHFJPY", PriceScale: 3, Description: "Swiss Franc vs Japanese Yen"},
	{ID: 26, Name: "NZD/JPY", Code: "NZDJPY", PriceScale: 3, Description: "New Zealand Dollar vs Japanese Yen"},
	{ID: 27, Name: "NZD/CHF", Code: "NZDCHF", PriceScale: 5, Description: "New Zealand Dollar vs Swiss Franc"},
	{ID: 28, Name: "NZD/CAD", Code: "NZDCAD", PriceScale: 5, Description: "New Zealand Dollar vs Canadian Dollar"},

	// Forex Exotic Pairs
	{ID: 29, Name: "USD/TRY", Code: "USDTRY", PriceScale: 5, Description: "US Dollar vs Turkish Lira"},
	{ID: 30, Name: "EUR/TRY", Code: "EURTRY", PriceScale: 5, Description: "Euro vs Turkish Lira"},
	{ID: 31, Name: "GBP/TRY", Code: "GBPTRY", PriceScale: 5, Description: "Great Britain Pound vs Turkish Lira"},
	{ID: 32, Name: "USD/MXN", Code: "USDMXN", PriceScale: 5, Description: "US Dollar vs Mexican Peso"},
	{ID: 33, Name: "EUR/MXN", Code: "EURMXN", PriceScale: 5, Description: "Euro vs Mexican Peso"},
	{ID: 34, Name: "GBP/MXN", Code: "GBPMXN", PriceScale: 5, Description: "Great Britain Pound vs Mexican Peso"},
	{ID: 35, Name: "USD/ZAR", Code: "USDZAR", PriceScale: 5, Description: "US Dollar vs South African Rand"},
	{ID: 36, Name: "EUR/ZAR", Code: "EURZAR", PriceScale: 5, Description: "Euro vs South African Rand"},
	{ID: 37, Name: "GBP/ZAR", Code: "GBPZAR", PriceScale: 5, Description: "Great Britain Pound vs South African Rand"},
	{ID: 38, Name: "USD/SGD", Code: "USDSGD", PriceScale: 5, Description: "US Dollar vs Singapore Dollar"},
	{ID: 39, Name: "EUR/SGD", Code: "EURSGD", PriceScale: 5, Description: "Euro vs Singapore Dollar"},
	{ID: 40, Name: "GBP/SGD", Code: "GBPSGD", PriceScale: 5, Description: "Great Britain Pound vs Singapore Dollar"},
	{ID: 41, Name: "USD/HKD", Code: "USDHKD", PriceScale: 5, Description: "US Dollar vs Hong Kong Dollar"},
	{ID: 42, Name: "EUR/HKD", Code: "EURHKD", PriceScale: 5, Description: "Euro vs Hong Kong Dollar"},
	{ID: 43, Name: "USD/CNH", Code: "USDCNH", PriceScale: 5, Description: "US Dollar vs Chinese Offshore Yuan"},
	{ID: 44, Name: "USD/SEK", Code: "USDSEK", PriceScale: 5, Description: "US Dollar vs Swedish Krona"},
	{ID: 45, Name: "EUR/SEK", Code: "EURSEK", PriceScale: 5, Description: "Euro vs Swedish Krona"},
	{ID: 46, Name: "GBP/SEK", Code: "GBPSEK", PriceScale: 5, Description: "Great Britain Pound vs Swedish Krona"},
	{ID: 47, Name: "USD/NOK", Code: "USDNOK", PriceScale: 5, Description: "US Dollar vs Norwegian Krone"},
	{ID: 48, Name: "EUR/NOK", Code: "EURNOK", PriceScale: 5, Description: "Euro vs Norwegian Krone"},
	{ID: 49, Name: "GBP/NOK", Code: "GBPNOK", PriceScale: 5, Description: "Great Britain Pound vs Norwegian Krone"},
	{ID: 50, Name: "USD/DKK", Code: "USDDKK", PriceScale: 5, Description: "US Dollar vs Danish Krone"},
	{ID: 51, Name: "EUR/DKK", Code: "EURDKK", PriceScale: 5, Description: "Euro vs Danish Krone"},
	{ID: 52, Name: "GBP/DKK", Code: "GBPDKK", PriceScale: 5, Description: "Great Britain Pound vs Danish Krone"},
	{ID: 53, Name: "USD/PLN", Code: "USDPLN", PriceScale: 5, Description: "US Dollar vs Polish Zloty"},
	{ID: 54, Name: "EUR/PLN", Code: "EURPLN", PriceScale: 5, Description: "Euro vs Polish Zloty"},
	{ID: 55, Name: "GBP/PLN", Code: "GBPPLN", PriceScale: 5, Description: "Great Britain Pound vs Polish Zloty"},
	{ID: 56, Name: "USD/RUB", Code: "USDRUB", PriceScale: 5, Description: "US Dollar vs Russian Ruble"},
	{ID: 57, Name: "EUR/RUB", Code: "EURRUB", PriceScale: 5, Description: "Euro vs Russian Ruble"},

	// Forex Cross JPY Pairs
	{ID: 58, Name: "SGD/JPY", Code: "SGDJPY", PriceScale: 3, Description: "Singapore Dollar vs Japanese Yen"},
	{ID: 59, Name: "HKD/JPY", Code: "HKDJPY", PriceScale: 3, Description: "Hong Kong Dollar vs Japanese Yen"},
	{ID: 60, Name: "NOK/JPY", Code: "NOKJPY", PriceScale: 3, Description: "Norwegian Krone vs Japanese Yen"},
	{ID: 61, Name: "SEK/JPY", Code: "SEKJPY", PriceScale: 3, Description: "Swedish Krona vs Japanese Yen"},
	{ID: 62, Name: "MXN/JPY", Code: "MXNJPY", PriceScale: 3, Description: "Mexican Peso vs Japanese Yen"},
	{ID: 63, Name: "TRY/JPY", Code: "TRYJPY", PriceScale: 3, Description: "Turkish Lira vs Japanese Yen"},
	{ID: 64, Name: "ZAR/JPY", Code: "ZARJPY", PriceScale: 3, Description: "South African Rand vs Japanese Yen"},
	{ID: 65, Name: "PLN/JPY", Code: "PLNJPY", PriceScale: 3, Description: "Polish Zloty vs Japanese Yen"},
	{ID: 66, Name: "AUD/SGD", Code: "AUDSGD", PriceScale: 5, Description: "Australian Dollar vs Singapore Dollar"},
	{ID: 67, Name: "CHF/SGD", Code: "CHFSGD", PriceScale: 5, Description: "Swiss Franc vs Singapore Dollar"},

	// Additional Forex Exotics
	{ID: 120, Name: "USD/HUF", Code: "USDHUF", PriceScale: 3, Description: "US Dollar vs Hungarian Forint"},
	{ID: 121, Name: "EUR/HUF", Code: "EURHUF", PriceScale: 3, Description: "Euro vs Hungarian Forint"},
	{ID: 122, Name: "USD/CZK", Code: "USDCZK", PriceScale: 4, Description: "US Dollar vs Czech Koruna"},
	{ID: 123, Name: "EUR/CZK", Code: "EURCZK", PriceScale: 4, Description: "Euro vs Czech Koruna"},
	{ID: 124, Name: "USD/RON", Code: "USDRON", PriceScale: 5, Description: "US Dollar vs Romanian Leu"},
	{ID: 125, Name: "EUR/RON", Code: "EURRON", PriceScale: 5, Description: "Euro vs Romanian Leu"},
	{ID: 126, Name: "USD/ILS", Code: "USDILS", PriceScale: 5, Description: "US Dollar vs Israeli Shekel"},
	{ID: 127, Name: "EUR/ILS", Code: "EURILS", PriceScale: 5, Description: "Euro vs Israeli Shekel"},
	{ID: 128, Name: "USD/THB", Code: "USDTHB", PriceScale: 4, Description: "US Dollar vs Thai Baht"},
	{ID: 129, Name: "USD/INR", Code: "USDINR", PriceScale: 4, Description: "US Dollar vs Indian Rupee"},
	{ID: 130, Name: "USD/KRW", Code: "USDKRW", PriceScale: 2, Description: "US Dollar vs South Korean Won"},
	{ID: 131, Name: "USD/BRL", Code: "USDBRL", PriceScale: 4, Description: "US Dollar vs Brazilian Real"},
	{ID: 132, Name: "USD/CLP", Code: "USDCLP", PriceScale: 2, Description: "US Dollar vs Chilean Peso"},
	{ID: 133, Name: "USD/COP", Code: "USDCOP", PriceScale: 2, Description: "US Dollar vs Colombian Peso"},
	{ID: 134, Name: "USD/PEN", Code: "USDPEN", PriceScale: 4, Description: "US Dollar vs Peruvian Sol"},
	{ID: 135, Name: "USD/SAR", Code: "USDSAR", PriceScale: 4, Description: "US Dollar vs Saudi Riyal"},
	{ID: 136, Name: "USD/AED", Code: "USDAED", PriceScale: 4, Description: "US Dollar vs UAE Dirham"},

	// Precious Metals
	{ID: 70, Name: "XAU/USD", Code: "XAUUSD", PriceScale: 3, Description: "Gold vs US Dollar"},
	{ID: 71, Name: "XAG/USD", Code: "XAGUSD", PriceScale: 3, Description: "Silver vs US Dollar"},
	{ID: 72, Name: "XPT/USD", Code: "XPTUSD", PriceScale: 3, Description: "Platinum vs US Dollar"},
	{ID: 73, Name: "XPD/USD", Code: "XPDUSD", PriceScale: 3, Description: "Palladium vs US Dollar"},
	{ID: 74, Name: "XAU/EUR", Code: "XAUEUR", PriceScale: 3, Description: "Gold vs Euro"},
	{ID: 75, Name: "XAG/EUR", Code: "XAGEUR", PriceScale: 3, Description: "Silver vs Euro"},

	// Commodities
	{ID: 80, Name: "BRENT.CMD/USD", Code: "BRENTCMDUSD", PriceScale: 3, Description: "Brent Crude Oil"},
	{ID: 81, Name: "LIGHT.CMD/USD", Code: "LIGHTCMDUSD", PriceScale: 3, Description: "Light Crude Oil"},
	{ID: 82, Name: "GAS.CMD/USD", Code: "GASCMDUSD", PriceScale: 3, Description: "Natural Gas"},
	{ID: 83, Name: "COPPER.CMD/USD", Code: "COPPERCMDUSD", PriceScale: 3, Description: "Copper"},
	{ID: 84, Name: "COCOA.CMD/USD", Code: "COCOACMDUSD", PriceScale: 1, Description: "Cocoa"},
	{ID: 85, Name: "COFFEE.CMD/USD", Code: "COFFEECMDUSD", PriceScale: 3, Description: "Coffee"},
	{ID: 86, Name: "COTTON.CMD/USD", Code: "COTTONCMDUSD", PriceScale: 3, Description: "Cotton"},
	{ID: 87, Name: "SUGAR.CMD/USD", Code: "SUGARCMDUSD", PriceScale: 4, Description: "Sugar"},
	{ID: 88, Name: "SOYENTS.CMD/USD", Code: "SOYENTSCMDUSD", PriceScale: 3, Description: "Soybeans"},
	{ID: 89, Name: "CORN.CMD/USD", Code: "CORNCMDUSD", PriceScale: 3, Description: "Corn"},
	{ID: 90, Name: "WHEAT.CMD/USD", Code: "WHEATCMDUSD", PriceScale: 3, Description: "Wheat"},
	
	// Additional Commodities
	{ID: 140, Name: "DIESEL.CMD/USD", Code: "DIESELCMDUSD", PriceScale: 3, Description: "Gasoil / Diesel"},
	{ID: 141, Name: "GASOLINE.CMD/USD", Code: "GASOLINECMDUSD", PriceScale: 3, Description: "Gasoline"},
	{ID: 142, Name: "HEATOIL.CMD/USD", Code: "HEATOILCMDUSD", PriceScale: 4, Description: "Heating Oil"},
	{ID: 143, Name: "OATS.CMD/USD", Code: "OATSCMDUSD", PriceScale: 3, Description: "Oats"},
	{ID: 144, Name: "ORANGE.CMD/USD", Code: "ORANGECMDUSD", PriceScale: 4, Description: "Orange Juice"},
	{ID: 145, Name: "RICE.CMD/USD", Code: "RICECMDUSD", PriceScale: 4, Description: "Rough Rice"},
	{ID: 146, Name: "SOYMEAL.CMD/USD", Code: "SOYMEALCMDUSD", PriceScale: 3, Description: "Soybean Meal"},
	{ID: 147, Name: "SOYOIL.CMD/USD", Code: "SOYOILCMDUSD", PriceScale: 4, Description: "Soybean Oil"},

	// Cryptocurrencies (USD-based)
	{ID: 95, Name: "BTC/USD", Code: "BTCUSD", PriceScale: 2, Description: "Bitcoin vs US Dollar"},
	{ID: 96, Name: "ETH/USD", Code: "ETHUSD", PriceScale: 2, Description: "Ethereum vs US Dollar"},
	{ID: 97, Name: "LTC/USD", Code: "LTCUSD", PriceScale: 2, Description: "Litecoin vs US Dollar"},
	{ID: 98, Name: "BCH/USD", Code: "BCHUSD", PriceScale: 2, Description: "Bitcoin Cash vs US Dollar"},
	{ID: 99, Name: "XRP/USD", Code: "XRPUSD", PriceScale: 4, Description: "Ripple vs US Dollar"},
	{ID: 100, Name: "ADA/USD", Code: "ADAUSD", PriceScale: 4, Description: "Cardano vs US Dollar"},
	{ID: 101, Name: "SOL/USD", Code: "SOLUSD", PriceScale: 2, Description: "Solana vs US Dollar"},
	{ID: 102, Name: "DOT/USD", Code: "DOTUSD", PriceScale: 3, Description: "Polkadot vs US Dollar"},
	{ID: 103, Name: "DOGE/USD", Code: "DOGEUSD", PriceScale: 5, Description: "Dogecoin vs US Dollar"},
	{ID: 104, Name: "XLM/USD", Code: "XLMUSD", PriceScale: 5, Description: "Stellar vs US Dollar"},
	{ID: 105, Name: "LINK/USD", Code: "LINKUSD", PriceScale: 3, Description: "Chainlink vs US Dollar"},
	{ID: 106, Name: "AVAX/USD", Code: "AVAXUSD", PriceScale: 2, Description: "Avalanche vs US Dollar"},
	{ID: 150, Name: "MATIC/USD", Code: "MATICUSD", PriceScale: 4, Description: "Polygon vs US Dollar"},
	{ID: 151, Name: "UNI/USD", Code: "UNIUSD", PriceScale: 3, Description: "Uniswap vs US Dollar"},
	{ID: 152, Name: "ALGO/USD", Code: "ALGOUSD", PriceScale: 4, Description: "Algorand vs US Dollar"},
	{ID: 153, Name: "ATOM/USD", Code: "ATOMUSD", PriceScale: 3, Description: "Cosmos vs US Dollar"},

	// Cryptocurrencies (EUR-based)
	{ID: 160, Name: "BTC/EUR", Code: "BTCEUR", PriceScale: 2, Description: "Bitcoin vs Euro"},
	{ID: 161, Name: "ETH/EUR", Code: "ETHEUR", PriceScale: 2, Description: "Ethereum vs Euro"},
	{ID: 162, Name: "LTC/EUR", Code: "LTCEUR", PriceScale: 2, Description: "Litecoin vs Euro"},
	{ID: 163, Name: "BCH/EUR", Code: "BCHEUR", PriceScale: 2, Description: "Bitcoin Cash vs Euro"},
	{ID: 164, Name: "XRP/EUR", Code: "XRPEUR", PriceScale: 4, Description: "Ripple vs Euro"},
	{ID: 165, Name: "SOL/EUR", Code: "SOLEUR", PriceScale: 2, Description: "Solana vs Euro"},
	{ID: 166, Name: "DOT/EUR", Code: "DOTEUR", PriceScale: 3, Description: "Polkadot vs Euro"},
	{ID: 167, Name: "DOGE/EUR", Code: "DOGEEUR", PriceScale: 5, Description: "Dogecoin vs Euro"},
	{ID: 168, Name: "LINK/EUR", Code: "LINKEUR", PriceScale: 3, Description: "Chainlink vs Euro"},
	{ID: 169, Name: "AVAX/EUR", Code: "AVAXEUR", PriceScale: 2, Description: "Avalanche vs Euro"},
	{ID: 170, Name: "MATIC/EUR", Code: "MATICEUR", PriceScale: 4, Description: "Polygon vs Euro"},
	{ID: 171, Name: "UNI/EUR", Code: "UNIEUR", PriceScale: 3, Description: "Uniswap vs Euro"},
	{ID: 172, Name: "ALGO/EUR", Code: "ALGOEUR", PriceScale: 4, Description: "Algorand vs Euro"},
	{ID: 173, Name: "ATOM/EUR", Code: "ATOMEUR", PriceScale: 3, Description: "Cosmos vs Euro"},

	// Indices
	{ID: 110, Name: "USA30.IDX/USD", Code: "USA30IDXUSD", PriceScale: 1, Description: "US Wall Street 30 Index"},
	{ID: 111, Name: "USA500.IDX/USD", Code: "USA500IDXUSD", PriceScale: 1, Description: "US SPX 500 Index"},
	{ID: 112, Name: "USATECH.IDX/USD", Code: "USATECHIDXUSD", PriceScale: 1, Description: "US Tech 100 Index"},
	{ID: 113, Name: "DEU.IDX/EUR", Code: "DEUIDXEUR", PriceScale: 1, Description: "Germany 30 Index"},
	{ID: 114, Name: "GBR.IDX/GBP", Code: "GBRIDXGBP", PriceScale: 1, Description: "UK 100 Index"},
	{ID: 115, Name: "FRA.IDX/EUR", Code: "FRAIDXEUR", PriceScale: 1, Description: "France 40 Index"},
	{ID: 116, Name: "JPN.IDX/JPY", Code: "JPNIDXJPY", PriceScale: 1, Description: "Japan 225 Index"},
	{ID: 117, Name: "ESP.IDX/EUR", Code: "ESPIDXEUR", PriceScale: 1, Description: "Spain 35 Index"},
	{ID: 118, Name: "AUS.IDX/AUD", Code: "AUSIDXAUD", PriceScale: 1, Description: "Australia 200 Index"},
	{ID: 119, Name: "EUS.IDX/EUR", Code: "EUSIDXEUR", PriceScale: 1, Description: "Europe 50 Index"},
	
	// Additional Global Indices
	{ID: 180, Name: "CHE.IDX/CHF", Code: "CHEIDXCHF", PriceScale: 1, Description: "Switzerland 20 Index"},
	{ID: 181, Name: "HKG.IDX/HKD", Code: "HKGIDXHKD", PriceScale: 1, Description: "Hong Kong 50 Index"},
	{ID: 182, Name: "NLD.IDX/EUR", Code: "NLDIDXEUR", PriceScale: 2, Description: "Netherlands 25 Index"},
	{ID: 183, Name: "ITA.IDX/EUR", Code: "ITAIDXEUR", PriceScale: 1, Description: "Italy 40 Index"},
	{ID: 184, Name: "SWE.IDX/SEK", Code: "SWEIDXSEK", PriceScale: 1, Description: "Sweden 30 Index"},
	{ID: 185, Name: "ZAF.IDX/ZAR", Code: "ZAFIDXZAR", PriceScale: 1, Description: "South Africa 40 Index"},
	{ID: 186, Name: "CAD.IDX/CAD", Code: "CADIDXCAD", PriceScale: 1, Description: "Canada 60 Index"},
	{ID: 187, Name: "SGP.IDX/SGD", Code: "SGPIDXSGD", PriceScale: 1, Description: "Singapore 30 Index"},
	{ID: 188, Name: "IND.IDX/USD", Code: "INDIDXUSD", PriceScale: 1, Description: "India 50 Index"},
	{ID: 189, Name: "CHI.IDX/USD", Code: "CHIIDXUSD", PriceScale: 1, Description: "China A50 Index"},
	{ID: 190, Name: "BRA.IDX/USD", Code: "BRAIDXUSD", PriceScale: 1, Description: "Brazil Index"},
	{ID: 191, Name: "MEX.IDX/USD", Code: "MEXIDXUSD", PriceScale: 1, Description: "Mexico Index"},

	// Major US Stock CFDs
	{ID: 200, Name: "AAPL.US/USD", Code: "AAPLUSUSD", PriceScale: 2, Description: "Apple Inc Stock"},
	{ID: 201, Name: "MSFT.US/USD", Code: "MSFTUSUSD", PriceScale: 2, Description: "Microsoft Corp Stock"},
	{ID: 202, Name: "GOOG.US/USD", Code: "GOOGUSUSD", PriceScale: 2, Description: "Alphabet Inc Stock"},
	{ID: 203, Name: "AMZN.US/USD", Code: "AMZNUSUSD", PriceScale: 2, Description: "Amazon.com Inc Stock"},
	{ID: 204, Name: "TSLA.US/USD", Code: "TSLAUSUSD", PriceScale: 2, Description: "Tesla Inc Stock"},
	{ID: 205, Name: "NVDA.US/USD", Code: "NVDAUSUSD", PriceScale: 2, Description: "NVIDIA Corp Stock"},
	{ID: 206, Name: "META.US/USD", Code: "METAUSUSD", PriceScale: 2, Description: "Meta Platforms Inc Stock"},
	{ID: 207, Name: "NFLX.US/USD", Code: "NFLXUSUSD", PriceScale: 2, Description: "Netflix Inc Stock"},
	{ID: 208, Name: "AMD.US/USD", Code: "AMDUSUSD", PriceScale: 2, Description: "Advanced Micro Devices Stock"},
	{ID: 209, Name: "INTC.US/USD", Code: "INTCUSUSD", PriceScale: 2, Description: "Intel Corp Stock"},
	{ID: 210, Name: "BABA.US/USD", Code: "BABAUSUSD", PriceScale: 2, Description: "Alibaba Group Stock"},
	{ID: 211, Name: "JPM.US/USD", Code: "JPMUSUSD", PriceScale: 2, Description: "JPMorgan Chase & Co Stock"},
	{ID: 212, Name: "V.US/USD", Code: "VUSUSD", PriceScale: 2, Description: "Visa Inc Stock"},
	{ID: 213, Name: "MA.US/USD", Code: "MAUSUSD", PriceScale: 2, Description: "Mastercard Inc Stock"},
	{ID: 214, Name: "DIS.US/USD", Code: "DISUSUSD", PriceScale: 2, Description: "Walt Disney Co Stock"},
	{ID: 215, Name: "KO.US/USD", Code: "KOUSUSD", PriceScale: 2, Description: "Coca-Cola Co Stock"},
	{ID: 216, Name: "PEP.US/USD", Code: "PEPUSUSD", PriceScale: 2, Description: "PepsiCo Inc Stock"},
	{ID: 217, Name: "WMT.US/USD", Code: "WMTUSUSD", PriceScale: 2, Description: "Walmart Inc Stock"},
	{ID: 218, Name: "XOM.US/USD", Code: "XOMUSUSD", PriceScale: 2, Description: "Exxon Mobil Corp Stock"},
	{ID: 219, Name: "CVX.US/USD", Code: "CVXUSUSD", PriceScale: 2, Description: "Chevron Corp Stock"},
}
